<script lang="ts">
    export const mainDesc = "asdsa";
</script>

<style>
    
    @font-face {
        font-family: 'Luticaprofile'; /*font 이름*/
        font-style: 'normal'; /* font 스타일 정의 (기울임, 일반) */
        font-weight: 400; /* font 굵기 정의 */
        /* 브라우저&디바이스 환경에 따른 font 파일 위치 정의 */
        src: url('font/gyonggicheonn.eot?#iefix') format('embedded-opentype'), /* IE6-IE8 */ url('font/gyonggicheonn_bold.otf') format('otf'),
        /*  Modern Browsers */ url('gyonggicheonn_bold.otf') format('otf'), /* Modern Browsers */ url('font/gyonggicheonn.ttf') format('truetype'),
        /* Safari, Android, iOS */
        
    }
    .maincard__main{
        color:white;
    }
    .maincard__wrap{
        height:100%;
        overflow : hidden;
        width: 100%;
    }
    .maincard__wrap__main{
        display:flex;
        justify-content: space-evenly;
        align-items: center;
        height: 100%;
    }
    .maincard__border{
        padding-bottom : min(100%,500px);
        position: relative;
        width: min(809px,100%);
        border: #444444 1px solid;
        border-radius: 2%;        
    }
    .shadow-drop-lr {
        -webkit-animation: shadow-drop-lr 0.4s cubic-bezier(0.250, 0.460, 0.450, 0.940) both;
        animation: shadow-drop-lr 0.4s cubic-bezier(0.250, 0.460, 0.450, 0.940) both;
    }
    .card__inside{
        border-radius: 2%;
        
        position:absolute;
        display: flex;
        flex-direction: column;
        height: 100%;
        width: 100%;
        align-content: space-between;
        justify-content: space-between;
        align-items: flex-start;
        background : url('/profile_a.png');
        background-size: cover;
    }
    .nick_name{
        color : white;
        font-family:'Luticaprofile'
    }
    .stack_name{
        color : white;
        font-family:'Luticaprofile';
        margin: 4px
    }
    .article_bottom{
        display: flex;
        flex-direction: row;
        align-items: center;
        justify-content: space-between;
        padding-top: 2%;
        padding-bottom :2%;
        width: 100%;
    }
    .article_div{
        color : white;
        font-family:'Luticaprofile';
        display:flex;
        flex-direction:column;
        padding-left: 2%;
        padding-right: 2%;
    }
    .stack{
        display:flex;
        flex-direction: column;
    }
    .main_container{
        margin-left : 5%;
        margin-top : 5%;
        padding : 2%;
    }
    .article > a{
        text-decoration : none;
        color:white;
    }
    .nick_name > a{
        text-decoration : none;
        color:white;
    }
    .inner_shadow{
        box-shadow: rgba(0, 0, 0, 0.4) 30px -70px 70px -28px inset
    }
    /* ----------------------------------------------
    * Generated by Animista on 2024-2-2 1:17:5
    * Licensed under FreeBSD License.
    * See http://animista.net/license for more info. 
    * w: http://animista.net, t: @cssanimista
    * ---------------------------------------------- */
    
    /**
    * ----------------------------------------
    * animation shadow-drop-lr
    * ----------------------------------------
    */
    @-webkit-keyframes shadow-drop-lr {
        0% {
            -webkit-box-shadow: 0 0 0 0 rgba(0, 0, 0, 0), 0 0 0 0 rgba(0, 0, 0, 0);
            box-shadow: 0 0 0 0 rgba(0, 0, 0, 0), 0 0 0 0 rgba(0, 0, 0, 0);
        }
        100% {
            -webkit-box-shadow: -12px 0 20px -12px rgba(0, 0, 0, 0.35), 12px 0 20px -12px rgba(0, 0, 0, 0.35);
            box-shadow: -12px 0 20px -12px rgba(0, 0, 0, 0.35), 12px 0 20px -12px rgba(0, 0, 0, 0.35);
        }
    }
    @keyframes shadow-drop-lr {
        0% {
            -webkit-box-shadow: 0 0 0 0 rgba(0, 0, 0, 0), 0 0 0 0 rgba(0, 0, 0, 0);
            box-shadow: 0 0 0 0 rgba(0, 0, 0, 0), 0 0 0 0 rgba(0, 0, 0, 0);
        }
        100% {
            -webkit-box-shadow: -12px 0 20px -12px rgba(0, 0, 0, 0.35), 12px 0 20px -12px rgba(0, 0, 0, 0.35);
            box-shadow: -12px 0 20px -12px rgba(0, 0, 0, 0.35), 12px 0 20px -12px rgba(0, 0, 0, 0.35);
        }
    }
    
    .puff-in-center {
        -webkit-animation: puff-in-center 0.7s cubic-bezier(0.420, 0.000, 0.745, 0.715) both;
        animation: puff-in-center 0.7s cubic-bezier(0.420, 0.000, 0.745, 0.715) both;
    }
    /* ----------------------------------------------
    * Generated by Animista on 2024-2-8 6:15:16
    * Licensed under FreeBSD License.
    * See http://animista.net/license for more info. 
    * w: http://animista.net, t: @cssanimista
    * ---------------------------------------------- */
    
    /**
    * ----------------------------------------
    * animation puff-in-center
    * ----------------------------------------
    */
    @-webkit-keyframes puff-in-center {
        0% {
            -webkit-transform: scale(2);
            transform: scale(2);
            -webkit-filter: blur(4px);
            filter: blur(4px);
            opacity: 0;
        }
        100% {
            -webkit-transform: scale(1);
            transform: scale(1);
            -webkit-filter: blur(0px);
            filter: blur(0px);
            opacity: 1;
        }
    }
    @keyframes puff-in-center {
        0% {
            -webkit-transform: scale(2);
            transform: scale(2);
            -webkit-filter: blur(4px);
            filter: blur(4px);
            opacity: 0;
        }
        100% {
            -webkit-transform: scale(1);
            transform: scale(1);
            -webkit-filter: blur(0px);
            filter: blur(0px);
            opacity: 1;
        }
    }
    
</style>
<div
    style="
    width: 100%;
    height: 100vh;
    display: flex;
    justify-content: center;
    align-items: center;
    overflow: hidden;
    background: linear-gradient(314deg, #00000a, #0a043f);
    background-size: cover;"
    class="maincard__main"
    >
    <div class="maincard__wrap">
        <div class="maincard__wrap__main puff-in-center">
            <div class="maincard__border shadow-drop-lr">
                <div class="card__inside inner_shadow">
                    <!-- 이하 카드 본문 -->
                    <div class="main_container ">
                        <div>
                            <h3 class = "nick_name" style="
                                margin-bottom : 1%;
                                font-size: 1.5em;
                            ">
                                Software Developer
                            </h3>
                            <h1 class = "nick_name" style="
                                font-size: 2.5em;
                            ">
                                <a href="https://github.com/LuticaCANARD">Lutica_CANARD</a>
                            </h1>
                        </div>
                        <div class = "stack">
                            <h3 class = "stack_name" style="
                                font-size: 1.5em;
                                margin-bottom : 1%;
                            ">
                                Rust
                            </h3>
                            <p3 class = "stack_name">
                                Node.js, Svelte, Bun <br/> 
                                PostgreSQL, Redis, AWS, Docker <br/>
                                C#, Unity <br/> 
                            </p3>
                            <p4 class = "stack_name">
                                I interested in Server & GPU Programming 
                            </p4>

                        </div> 
                    </div>
                    <div class="article_bottom">
                        <div class="article_div">
                            <p1 class= "article" style="
                                font-size: 0.85em;
                                margin-bottom: 1%;"
                            >
                                I'm Living in <a href="https://maps.app.goo.gl/393ewhYvVzh1f6qQ6">paju</a>, near <a href="https://maps.app.goo.gl/jSAL18mFud9hi42k7">Seoul, Korea.</a>
                            </p1>
                            <p2 class= "article"
                            style="
                                font-size: 0.75em;
                                margin-bottom: 1%;"
                            >
                                This card is using <a href="https://gongu.copyright.or.kr/gongu/wrt/wrt/view.do?wrtSn=13288411&menuNo=200195">경기천년제목체</a>
                            </p2>
                        </div>
                        <div class="article_div">
                            <p1 class= "article"
                            style="
                                font-size: 0.95rem;
                                margin-bottom: 1%;"
                            >
                                presan100@gmail.com
                            </p1>
                        </div>
                    </div>
                    
                </div>
            </div>
        </div>
    </div>
</div>